import type { Item } from './types';

export const ALL_ITEMS: Item[] = [
  // Animals
  { name: 'Cow', emoji: '🐄', soundFrequency: 180, color: 'bg-sky-200', textColor: 'text-sky-800' },
  { name: 'Pig', emoji: '🐖', soundFrequency: 320, color: 'bg-pink-200', textColor: 'text-pink-800' },
  { name: 'Dog', emoji: '🐕', soundFrequency: 250, color: 'bg-amber-200', textColor: 'text-amber-800' },
  { name: 'Cat', emoji: '🐈', soundFrequency: 440, color: 'bg-slate-300', textColor: 'text-slate-800' },
  { name: 'Sheep', emoji: '🐑', soundFrequency: 380, color: 'bg-lime-200', textColor: 'text-lime-800' },
  { name: 'Lion', emoji: '🦁', soundFrequency: 200, color: 'bg-orange-300', textColor: 'text-orange-900' },
  { name: 'Monkey', emoji: '🐒', soundFrequency: 460, color: 'bg-yellow-400', textColor: 'text-yellow-900' },
  { name: 'Elephant', emoji: '🐘', soundFrequency: 140, color: 'bg-gray-400', textColor: 'text-gray-900' },
  { name: 'Giraffe', emoji: '🦒', soundFrequency: 230, color: 'bg-yellow-300', textColor: 'text-yellow-800' },
  
  // Fruits
  { name: 'Apple', emoji: '🍎', soundFrequency: 400, color: 'bg-red-200', textColor: 'text-red-800' },
  { name: 'Banana', emoji: '🍌', soundFrequency: 420, color: 'bg-yellow-200', textColor: 'text-yellow-800' },
  { name: 'Strawberry', emoji: '🍓', soundFrequency: 450, color: 'bg-red-300', textColor: 'text-red-900' },
  { name: 'Orange', emoji: '🍊', soundFrequency: 480, color: 'bg-orange-200', textColor: 'text-orange-800' },
  { name: 'Grapes', emoji: '🍇', soundFrequency: 500, color: 'bg-purple-200', textColor: 'text-purple-800' },

  // Vegetables
  { name: 'Carrot', emoji: '🥕', soundFrequency: 300, color: 'bg-orange-300', textColor: 'text-orange-900' },
  { name: 'Broccoli', emoji: '🥦', soundFrequency: 330, color: 'bg-green-200', textColor: 'text-green-800' },
  { name: 'Tomato', emoji: '🍅', soundFrequency: 350, color: 'bg-red-400', textColor: 'text-red-900' },
  { name: 'Potato', emoji: '🥔', soundFrequency: 280, color: 'bg-yellow-400', textColor: 'text-yellow-900' },
  { name: 'Bell Pepper', emoji: '🫑', soundFrequency: 370, color: 'bg-green-300', textColor: 'text-green-900' },

  // Transport
  { name: 'Car', emoji: '🚗', soundFrequency: 200, color: 'bg-blue-200', textColor: 'text-blue-800' },
  { name: 'Bus', emoji: '🚌', soundFrequency: 150, color: 'bg-yellow-300', textColor: 'text-yellow-900' },
  { name: 'Airplane', emoji: '✈️', soundFrequency: 600, color: 'bg-gray-200', textColor: 'text-gray-800' },
  { name: 'Train', emoji: '🚂', soundFrequency: 220, color: 'bg-red-300', textColor: 'text-red-800' },
  { name: 'Boat', emoji: '⛵️', soundFrequency: 340, color: 'bg-cyan-200', textColor: 'text-cyan-800' },
  { name: 'Rocket', emoji: '🚀', soundFrequency: 650, color: 'bg-slate-500', textColor: 'text-slate-100' },

  // Nature
  { name: 'Sun', emoji: '☀️', soundFrequency: 550, color: 'bg-yellow-200', textColor: 'text-yellow-800' },
  { name: 'Star', emoji: '⭐', soundFrequency: 700, color: 'bg-yellow-300', textColor: 'text-yellow-900' },
  { name: 'Flower', emoji: '🌻', soundFrequency: 520, color: 'bg-green-200', textColor: 'text-green-800' },
  { name: 'Tree', emoji: '🌳', soundFrequency: 160, color: 'bg-lime-300', textColor: 'text-lime-900' },

  // Objects
  { name: 'Ball', emoji: '⚽️', soundFrequency: 310, color: 'bg-gray-200', textColor: 'text-gray-800' },
  { name: 'Balloon', emoji: '🎈', soundFrequency: 470, color: 'bg-red-300', textColor: 'text-red-900' },
  { name: 'Gift', emoji: '🎁', soundFrequency: 530, color: 'bg-teal-200', textColor: 'text-teal-800' },
  { name: 'Book', emoji: '📚', soundFrequency: 270, color: 'bg-blue-300', textColor: 'text-blue-900' },

  // Instruments
  { name: 'Guitar', emoji: '🎸', soundFrequency: 260, color: 'bg-amber-300', textColor: 'text-amber-900' },
  { name: 'Piano', emoji: '🎹', soundFrequency: 490, color: 'bg-gray-300', textColor: 'text-gray-900' },
  { name: 'Drum', emoji: '🥁', soundFrequency: 190, color: 'bg-cyan-300', textColor: 'text-cyan-900' },

  // More Animals
  { name: 'Bear', emoji: '🐻', soundFrequency: 170, color: 'bg-amber-400', textColor: 'text-amber-900' },
  { name: 'Tiger', emoji: '🐅', soundFrequency: 210, color: 'bg-orange-400', textColor: 'text-orange-900' },
  { name: 'Rabbit', emoji: '🐰', soundFrequency: 360, color: 'bg-pink-300', textColor: 'text-pink-900' },
  { name: 'Duck', emoji: '🦆', soundFrequency: 290, color: 'bg-yellow-400', textColor: 'text-yellow-900' },
  { name: 'Frog', emoji: '🐸', soundFrequency: 380, color: 'bg-green-400', textColor: 'text-green-900' },
  { name: 'Fish', emoji: '🐟', soundFrequency: 240, color: 'bg-blue-300', textColor: 'text-blue-900' },

  // More Food
  { name: 'Pizza', emoji: '🍕', soundFrequency: 390, color: 'bg-orange-300', textColor: 'text-orange-900' },
  { name: 'Cake', emoji: '🍰', soundFrequency: 410, color: 'bg-pink-200', textColor: 'text-pink-800' },
  { name: 'Ice Cream', emoji: '🍦', soundFrequency: 430, color: 'bg-blue-200', textColor: 'text-blue-800' },
  { name: 'Cookie', emoji: '🍪', soundFrequency: 350, color: 'bg-amber-200', textColor: 'text-amber-800' },
  { name: 'Sandwich', emoji: '🥪', soundFrequency: 320, color: 'bg-yellow-300', textColor: 'text-yellow-900' },
  { name: 'Hot Dog', emoji: '🌭', soundFrequency: 340, color: 'bg-red-300', textColor: 'text-red-900' },

  // More Objects
  { name: 'House', emoji: '🏠', soundFrequency: 180, color: 'bg-red-200', textColor: 'text-red-800' },
  { name: 'Heart', emoji: '❤️', soundFrequency: 440, color: 'bg-red-400', textColor: 'text-red-100' },
  { name: 'Crown', emoji: '👑', soundFrequency: 520, color: 'bg-yellow-400', textColor: 'text-yellow-900' },
  { name: 'Key', emoji: '🗝️', soundFrequency: 300, color: 'bg-yellow-300', textColor: 'text-yellow-900' },
  { name: 'Clock', emoji: '🕐', soundFrequency: 280, color: 'bg-blue-300', textColor: 'text-blue-900' },
  { name: 'Phone', emoji: '📱', soundFrequency: 460, color: 'bg-gray-300', textColor: 'text-gray-900' },

  // Even More Animals
  { name: 'Horse', emoji: '🐴', soundFrequency: 220, color: 'bg-amber-300', textColor: 'text-amber-900' },
  { name: 'Panda', emoji: '🐼', soundFrequency: 190, color: 'bg-gray-200', textColor: 'text-gray-800' },
  { name: 'Koala', emoji: '🐨', soundFrequency: 250, color: 'bg-gray-300', textColor: 'text-gray-900' },
  { name: 'Penguin', emoji: '🐧', soundFrequency: 270, color: 'bg-slate-300', textColor: 'text-slate-900' },
  { name: 'Owl', emoji: '🦉', soundFrequency: 310, color: 'bg-amber-400', textColor: 'text-amber-900' },
  { name: 'Butterfly', emoji: '🦋', soundFrequency: 480, color: 'bg-purple-200', textColor: 'text-purple-800' },

  // More Food
  { name: 'Hamburger', emoji: '🍔', soundFrequency: 370, color: 'bg-yellow-400', textColor: 'text-yellow-900' },
  { name: 'Donut', emoji: '🍩', soundFrequency: 420, color: 'bg-pink-300', textColor: 'text-pink-900' },
  { name: 'Lollipop', emoji: '🍭', soundFrequency: 450, color: 'bg-pink-200', textColor: 'text-pink-800' },
  { name: 'Candy', emoji: '🍬', soundFrequency: 470, color: 'bg-red-200', textColor: 'text-red-800' },
  { name: 'Popcorn', emoji: '🍿', soundFrequency: 400, color: 'bg-yellow-300', textColor: 'text-yellow-900' },
  { name: 'Pretzel', emoji: '🥨', soundFrequency: 380, color: 'bg-amber-200', textColor: 'text-amber-800' },

  // More Objects
  { name: 'Umbrella', emoji: '☂️', soundFrequency: 330, color: 'bg-blue-200', textColor: 'text-blue-800' },
  { name: 'Rainbow', emoji: '🌈', soundFrequency: 540, color: 'bg-gradient-to-r from-red-200 to-purple-200', textColor: 'text-purple-800' },
  { name: 'Moon', emoji: '🌙', soundFrequency: 480, color: 'bg-slate-200', textColor: 'text-slate-800' },
  { name: 'Cloud', emoji: '☁️', soundFrequency: 360, color: 'bg-gray-200', textColor: 'text-gray-800' },
  { name: 'Snowflake', emoji: '❄️', soundFrequency: 420, color: 'bg-blue-100', textColor: 'text-blue-600' },
  { name: 'Fire', emoji: '🔥', soundFrequency: 580, color: 'bg-red-300', textColor: 'text-red-900' },
];

export const translations: Record<string, Record<string, string>> = {
  en: {
    Settings: 'Settings',
    language: 'Language',
    itemCount: 'Number of items',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    selectGame: 'Teo Games',
    popItGameTitle: 'Name It!',
    findItGameTitle: 'Find It!',
    vroomGameTitle: 'Vroom!',
    launches: 'launches',
    findThe: 'Where is',
    correct: 'right',
    total: 'total',
    amazing: 'Amazing!',
    great: 'Great job!',
    good: 'Good work!',
    keepGoing: 'Keep going!',
    learning: 'Keep learning!',
    Cow: 'Cow', Pig: 'Pig', Dog: 'Dog', Cat: 'Cat', Sheep: 'Sheep', Lion: 'Lion', Monkey: 'Monkey', Elephant: 'Elephant', Giraffe: 'Giraffe',
    Apple: 'Apple', Banana: 'Banana', Strawberry: 'Strawberry', Orange: 'Orange', Grapes: 'Grapes',
    Carrot: 'Carrot', Broccoli: 'Broccoli', Tomato: 'Tomato', Potato: 'Potato', 'Bell Pepper': 'Bell Pepper',
    Car: 'Car', Bus: 'Bus', Airplane: 'Airplane', Train: 'Train', Boat: 'Boat', Rocket: 'Rocket',
    Sun: 'Sun', Star: 'Star', Flower: 'Flower', Tree: 'Tree',
    Ball: 'Ball', Balloon: 'Balloon', Gift: 'Gift', Book: 'Book',
    Guitar: 'Guitar', Piano: 'Piano', Drum: 'Drum',
    Bear: 'Bear', Tiger: 'Tiger', Rabbit: 'Rabbit', Duck: 'Duck', Frog: 'Frog', Fish: 'Fish',
    Pizza: 'Pizza', Cake: 'Cake', 'Ice Cream': 'Ice Cream', Cookie: 'Cookie', Sandwich: 'Sandwich', 'Hot Dog': 'Hot Dog',
    House: 'House', Heart: 'Heart', Crown: 'Crown', Key: 'Key', Clock: 'Clock', Phone: 'Phone',
    Horse: 'Horse', Panda: 'Panda', Koala: 'Koala', Penguin: 'Penguin', Owl: 'Owl', Butterfly: 'Butterfly',
    Hamburger: 'Hamburger', Donut: 'Donut', Lollipop: 'Lollipop', Candy: 'Candy', Popcorn: 'Popcorn', Pretzel: 'Pretzel',
    Umbrella: 'Umbrella', Rainbow: 'Rainbow', Moon: 'Moon', Cloud: 'Cloud', Snowflake: 'Snowflake', Fire: 'Fire',
  },
  lv: {
    Settings: 'Iestatījumi',
    language: 'Valoda',
    itemCount: 'Objektu skaits',
    difficulty: 'Grūtības pakāpe',
    easy: 'Viegli',
    medium: 'Vidēji',
    hard: 'Grūti',
    selectGame: 'Teo spēles',
    popItGameTitle: 'Kas?',
    findItGameTitle: 'Kur?',
    vroomGameTitle: 'Brrūm!',
    launches: 'palaisti',
    findThe: 'Kur ir',
    correct: 'pareizi',
    total: 'kopā',
    amazing: 'Lieliski!',
    great: 'Lielisks darbs!',
    good: 'Labi!',
    keepGoing: 'Turpiniet!',
    learning: 'Mācieties tālāk!',
    Cow: 'Govs', Pig: 'Cūka', Dog: 'Suns', Cat: 'Kaķis', Sheep: 'Aita', Lion: 'Lauva', Monkey: 'Pērtiķis', Elephant: 'Zilonis', Giraffe: 'Žirafe',
    Apple: 'Ābols', Banana: 'Banāns', Strawberry: 'Zemene', Orange: 'Apelsīns', Grapes: 'Vīnogas',
    Carrot: 'Burkāns', Broccoli: 'Brokolis', Tomato: 'Tomāts', Potato: 'Kartupelis', 'Bell Pepper': 'Paprika',
    Car: 'Mašīna', Bus: 'Autobuss', Airplane: 'Lidmašīna', Train: 'Vilciens', Boat: 'Laiva', Rocket: 'Raķete',
    Sun: 'Saule', Star: 'Zvaigzne', Flower: 'Puķe', Tree: 'Koks',
    Ball: 'Bumba', Balloon: 'Balons', Gift: 'Dāvana', Book: 'Grāmata',
    Guitar: 'Ģitāra', Piano: 'Klavieres', Drum: 'Bungas',
    Bear: 'Lācis', Tiger: 'Tīģeris', Rabbit: 'Trusis', Duck: 'Pīlīte', Frog: 'Varde', Fish: 'Zivs',
    Pizza: 'Pica', Cake: 'Kūka', 'Ice Cream': 'Saldējums', Cookie: 'Cepums', Sandwich: 'Sviestmaize', 'Hot Dog': 'Hotdogs',
    House: 'Māja', Heart: 'Sirds', Crown: 'Kronis', Key: 'Atslēga', Clock: 'Pulkstenis', Phone: 'Tālrunis',
    Horse: 'Zirgs', Panda: 'Panda', Koala: 'Koala', Penguin: 'Pingvīns', Owl: 'Pūce', Butterfly: 'Tauriņš',
    Hamburger: 'Hamburgers', Donut: 'Donuts', Lollipop: 'Ledenīte', Candy: 'Konfekte', Popcorn: 'Popkorns', Pretzel: 'Brecelis',
    Umbrella: 'Lietussargs', Rainbow: 'Varavīksne', Moon: 'Mēness', Cloud: 'Mākonis', Snowflake: 'Sniegpārsla', Fire: 'Uguns',
  },
  es: {
    Settings: 'Ajustes',
    language: 'Idioma',
    itemCount: 'Número de objetos',
    difficulty: 'Dificultad',
    easy: 'Fácil',
    medium: 'Medio',
    hard: 'Difícil',
    selectGame: 'Teo Juegos',
    popItGameTitle: '¡Nómbralo!',
    findItGameTitle: '¡Encuéntralo!',
    vroomGameTitle: '¡Vroom!',
    launches: 'lanzamientos',
    findThe: '¿Dónde está',
    correct: 'correctas',
    total: 'total',
    amazing: '¡Increíble!',
    great: '¡Excelente!',
    good: '¡Bien!',
    keepGoing: '¡Sigue así!',
    learning: '¡Sigue aprendiendo!',
    Cow: 'Vaca', Pig: 'Cerdo', Dog: 'Perro', Cat: 'Gato', Sheep: 'Oveja', Lion: 'León', Monkey: 'Mono', Elephant: 'Elefante', Giraffe: 'Jirafa',
    Apple: 'Manzana', Banana: 'Plátano', Strawberry: 'Fresa', Orange: 'Naranja', Grapes: 'Uvas',
    Carrot: 'Zanahoria', Broccoli: 'Brócoli', Tomato: 'Tomate', Potato: 'Patata', 'Bell Pepper': 'Pimiento',
    Car: 'Coche', Bus: 'Autobús', Airplane: 'Avión', Train: 'Tren', Boat: 'Barco', Rocket: 'Cohete',
    Sun: 'Sol', Star: 'Estrella', Flower: 'Flor', Tree: 'Árbol',
    Ball: 'Pelota', Balloon: 'Globo', Gift: 'Regalo', Book: 'Libro',
    Guitar: 'Guitarra', Piano: 'Piano', Drum: 'Tambor',
    Bear: 'Oso', Tiger: 'Tigre', Rabbit: 'Conejo', Duck: 'Pato', Frog: 'Rana', Fish: 'Pez',
    Pizza: 'Pizza', Cake: 'Pastel', 'Ice Cream': 'Helado', Cookie: 'Galleta', Sandwich: 'Sándwich', 'Hot Dog': 'Perro Caliente',
    House: 'Casa', Heart: 'Corazón', Crown: 'Corona', Key: 'Llave', Clock: 'Reloj', Phone: 'Teléfono',
    Horse: 'Caballo', Panda: 'Panda', Koala: 'Koala', Penguin: 'Pingüino', Owl: 'Búho', Butterfly: 'Mariposa',
    Hamburger: 'Hamburguesa', Donut: 'Donut', Lollipop: 'Piruleta', Candy: 'Dulce', Popcorn: 'Palomitas', Pretzel: 'Pretzel',
    Umbrella: 'Paraguas', Rainbow: 'Arcoíris', Moon: 'Luna', Cloud: 'Nube', Snowflake: 'Copo de nieve', Fire: 'Fuego',
  },
  fr: {
    Settings: 'Paramètres',
    language: 'Langue',
    itemCount: "Nombre d'objets",
    difficulty: 'Difficulté',
    easy: 'Facile',
    medium: 'Moyen',
    hard: 'Difficile',
    selectGame: 'Teo Jeux',
    popItGameTitle: 'Nomme-le !',
    findItGameTitle: 'Trouve-le !',
    vroomGameTitle: 'Vroum !',
    launches: 'lancements',
    findThe: 'Où est',
    correct: 'correctes',
    total: 'total',
    amazing: 'Incroyable !',
    great: 'Excellent !',
    good: 'Bien !',
    keepGoing: 'Continue !',
    learning: 'Continue d\'apprendre !',
    Cow: 'Vache', Pig: 'Cochon', Dog: 'Chien', Cat: 'Chat', Sheep: 'Mouton', Lion: 'Lion', Monkey: 'Singe', Elephant: 'Éléphant', Giraffe: 'Girafe',
    Apple: 'Pomme', Banana: 'Banane', Strawberry: 'Fraise', Orange: 'Orange', Grapes: 'Raisins',
    Carrot: 'Carotte', Broccoli: 'Brocoli', Tomato: 'Tomate', 'Bell Pepper': 'Poivron', Potato: 'Pomme de terre',
    Car: 'Voiture', Bus: 'Bus', Airplane: 'Avion', Train: 'Train', Boat: 'Bateau', Rocket: 'Fusée',
    Sun: 'Soleil', Star: 'Étoile', Flower: 'Fleur', Tree: 'Arbre',
    Ball: 'Balle', Balloon: 'Ballon', Gift: 'Cadeau', Book: 'Livre',
    Guitar: 'Guitare', Piano: 'Piano', Drum: 'Tambour',
    Bear: 'Ours', Tiger: 'Tigre', Rabbit: 'Lapin', Duck: 'Canard', Frog: 'Grenouille', Fish: 'Poisson',
    Pizza: 'Pizza', Cake: 'Gâteau', 'Ice Cream': 'Glace', Cookie: 'Biscuit', Sandwich: 'Sandwich', 'Hot Dog': 'Hot Dog',
    House: 'Maison', Heart: 'Cœur', Crown: 'Couronne', Key: 'Clé', Clock: 'Horloge', Phone: 'Téléphone',
    Horse: 'Cheval', Panda: 'Panda', Koala: 'Koala', Penguin: 'Manchot', Owl: 'Hibou', Butterfly: 'Papillon',
    Hamburger: 'Hamburger', Donut: 'Donut', Lollipop: 'Sucette', Candy: 'Bonbon', Popcorn: 'Popcorn', Pretzel: 'Bretzel',
    Umbrella: 'Parapluie', Rainbow: 'Arc-en-ciel', Moon: 'Lune', Cloud: 'Nuage', Snowflake: 'Flocon de neige', Fire: 'Feu',
  },
  de: {
    Settings: 'Einstellungen',
    language: 'Sprache',
    itemCount: 'Anzahl der Objekte',
    difficulty: 'Schwierigkeit',
    easy: 'Leicht',
    medium: 'Mittel',
    hard: 'Schwer',
    selectGame: 'Teo Spiele',
    popItGameTitle: 'Benenne es!',
    findItGameTitle: 'Finde es!',
    vroomGameTitle: 'Brumm!',
    launches: 'Starts',
    findThe: 'Wo ist',
    correct: 'richtig',
    total: 'gesamt',
    amazing: 'Unglaublich!',
    great: 'Großartig!',
    good: 'Gut!',
    keepGoing: 'Weiter so!',
    learning: 'Lerne weiter!',
    Cow: 'Kuh', Pig: 'Schwein', Dog: 'Hund', Cat: 'Katze', Sheep: 'Schaf', Lion: 'Löwe', Monkey: 'Affe', Elephant: 'Elefant', Giraffe: 'Giraffe',
    Apple: 'Apfel', Banana: 'Banane', Strawberry: 'Erdbeere', Orange: 'Orange', Grapes: 'Trauben',
    Carrot: 'Karotte', Broccoli: 'Brokkoli', Tomato: 'Tomate', Potato: 'Kartoffel', 'Bell Pepper': 'Paprika',
    Car: 'Auto', Bus: 'Bus', Airplane: 'Flugzeug', Train: 'Zug', Boat: 'Boot', Rocket: 'Rakete',
    Sun: 'Sonne', Star: 'Stern', Flower: 'Blume', Tree: 'Baum',
    Ball: 'Ball', Balloon: 'Luftballon', Gift: 'Geschenk', Book: 'Buch',
    Guitar: 'Gitarre', Piano: 'Klavier', Drum: 'Trommel',
    Bear: 'Bär', Tiger: 'Tiger', Rabbit: 'Hase', Duck: 'Ente', Frog: 'Frosch', Fish: 'Fisch',
    Pizza: 'Pizza', Cake: 'Kuchen', 'Ice Cream': 'Eis', Cookie: 'Keks', Sandwich: 'Sandwich', 'Hot Dog': 'Hot Dog',
    House: 'Haus', Heart: 'Herz', Crown: 'Krone', Key: 'Schlüssel', Clock: 'Uhr', Phone: 'Telefon',
    Horse: 'Pferd', Panda: 'Panda', Koala: 'Koala', Penguin: 'Pinguin', Owl: 'Eule', Butterfly: 'Schmetterling',
    Hamburger: 'Hamburger', Donut: 'Donut', Lollipop: 'Lutscher', Candy: 'Süßigkeit', Popcorn: 'Popcorn', Pretzel: 'Brezel',
    Umbrella: 'Regenschirm', Rainbow: 'Regenbogen', Moon: 'Mond', Cloud: 'Wolke', Snowflake: 'Schneeflocke', Fire: 'Feuer',
  },
  et: {
    Settings: 'Seaded',
    language: 'Keel',
    itemCount: 'Objektide arv',
    difficulty: 'Raskusaste',
    easy: 'Kerge',
    medium: 'Keskmine',
    hard: 'Raske',
    selectGame: 'Teo Mängud',
    popItGameTitle: 'Mis?',
    findItGameTitle: 'Kus?',
    vroomGameTitle: 'Prrrõm!',
    launches: 'käivitust',
    findThe: 'Kus on',
    correct: 'õige',
    total: 'kokku',
    amazing: 'Hämmastav!',
    great: 'Suurepärane!',
    good: 'Hea!',
    keepGoing: 'Jätka!',
    learning: 'Õpi edasi!',
    Cow: 'Lehm', Pig: 'Siga', Dog: 'Koer', Cat: 'Kass', Sheep: 'Lammas', Lion: 'Lõvi', Monkey: 'Ahv', Elephant: 'Elevant', Giraffe: 'Kaelkirjak',
    Apple: 'Õun', Banana: 'Banaan', Strawberry: 'Maasikas', Orange: 'Apelsin', Grapes: 'Viinamarjad',
    Carrot: 'Porgand', Broccoli: 'Brokoli', Tomato: 'Tomat', Potato: 'Kartul', 'Bell Pepper': 'Paprika',
    Car: 'Auto', Bus: 'Buss', Airplane: 'Lennuk', Train: 'Rong', Boat: 'Paat', Rocket: 'Rakett',
    Sun: 'Päikes', Star: 'Täht', Flower: 'Lill', Tree: 'Puu',
    Ball: 'Pall', Balloon: 'Õhupall', Gift: 'Kingitus', Book: 'Raamat',
    Guitar: 'Kitarr', Piano: 'Klaver', Drum: 'Trumm',
    Bear: 'Karu', Tiger: 'Tiiger', Rabbit: 'Jänes', Duck: 'Part', Frog: 'Konn', Fish: 'Kala',
    Pizza: 'Pitsa', Cake: 'Kook', 'Ice Cream': 'Jäätis', Cookie: 'Küpsis', Sandwich: 'Võileib', 'Hot Dog': 'Hotdog',
    House: 'Maja', Heart: 'Süda', Crown: 'Kroon', Key: 'Võti', Clock: 'Kell', Phone: 'Telefon',
    Horse: 'Hobune', Panda: 'Panda', Koala: 'Koaala', Penguin: 'Pingviin', Owl: 'Öökull', Butterfly: 'Liblikas',
    Hamburger: 'Hamburger', Donut: 'Sõõrik', Lollipop: 'Pulgakomm', Candy: 'Komm', Popcorn: 'Popkorn', Pretzel: 'Kringel',
    Umbrella: 'Vihmavari', Rainbow: 'Vikerkaar', Moon: 'Kuu', Cloud: 'Pilv', Snowflake: 'Lumehelves', Fire: 'Tuli',
  },
  lt: {
    Settings: 'Nustatymai',
    language: 'Kalba',
    itemCount: 'Objektų skaičius',
    difficulty: 'Sudėtingumas',
    easy: 'Lengva',
    medium: 'Vidutinė',
    hard: 'Sunki',
    selectGame: 'Teo Žaidimai',
    popItGameTitle: 'Kas?',
    findItGameTitle: 'Kur?',
    vroomGameTitle: 'Brrūm!',
    launches: 'paleidimai',
    findThe: 'Kur yra',
    correct: 'teisingai',
    total: 'viso',
    amazing: 'Nuostabu!',
    great: 'Puiku!',
    good: 'Gerai!',
    keepGoing: 'Pirmyn!',
    learning: 'Mokykis toliau!',
    Cow: 'Karvė', Pig: 'Kiaulė', Dog: 'Šuo', Cat: 'Katė', Sheep: 'Avis', Lion: 'Liūtas', Monkey: 'Beždžionė', Elephant: 'Dramblys', Giraffe: 'Žirafa',
    Apple: 'Obuolys', Banana: 'Bananas', Strawberry: 'Braškė', Orange: 'Apelsinas', Grapes: 'Vynuogės',
    Carrot: 'Morka', Broccoli: 'Brokolis', Tomato: 'Pomidoras', Potato: 'Bulvė', 'Bell Pepper': 'Paprika',
    Car: 'Automobilis', Bus: 'Autobusas', Airplane: 'Lėktuvas', Train: 'Traukinys', Boat: 'Valtis', Rocket: 'Raketa',
    Sun: 'Saulė', Star: 'Žvaigždė', Flower: 'Gėlė', Tree: 'Medis',
    Ball: 'Kamuolys', Balloon: 'Balionas', Gift: 'Dovana', Book: 'Knyga',
    Guitar: 'Gitara', Piano: 'Pianinas', Drum: 'Būgnas',
    Bear: 'Lokys', Tiger: 'Tigras', Rabbit: 'Zuikis', Duck: 'Antis', Frog: 'Varlė', Fish: 'Žuvis',
    Pizza: 'Pica', Cake: 'Tortas', 'Ice Cream': 'Ledai', Cookie: 'Sausainis', Sandwich: 'Sumuštinis', 'Hot Dog': 'Dešrainis',
    House: 'Namas', Heart: 'Širdis', Crown: 'Karūna', Key: 'Raktas', Clock: 'Laikrodis', Phone: 'Telefonas',
    Horse: 'Arklys', Panda: 'Panda', Koala: 'Koala', Penguin: 'Pingvinas', Owl: 'Pelėda', Butterfly: 'Drugelis',
    Hamburger: 'Mėsainis', Donut: 'Spurga', Lollipop: 'Ledinukas', Candy: 'Saldainis', Popcorn: 'Spragėsiai', Pretzel: 'Riestainys',
    Umbrella: 'Skėtis', Rainbow: 'Vaivorykštė', Moon: 'Mėnulis', Cloud: 'Debesis', Snowflake: 'Snaigė', Fire: 'Ugnis',
  }
};

// Simplified phonetic pronunciations for each language
// Helps parents pronounce words correctly for their toddler
export const pronunciations: Record<string, Record<string, string>> = {
  en: {
    Cow: 'kau', Pig: 'pig', Dog: 'dog', Cat: 'kat', Sheep: 'shiip', Lion: 'lai-ən', Monkey: 'man-ki', Elephant: 'el-ə-fənt', Giraffe: 'jə-raaf',
    Apple: 'ap-əl', Banana: 'bə-naa-nə', Strawberry: 'stro-be-ri', Orange: 'or-inj', Grapes: 'greips',
    Carrot: 'ka-rət', Broccoli: 'bro-kə-li', Tomato: 'tə-mei-to', Potato: 'pə-tei-to', 'Bell Pepper': 'bel pe-pər',
    Car: 'kaar', Bus: 'bas', Airplane: 'er-plein', Train: 'trein', Boat: 'bout', Rocket: 'ro-kit',
    Sun: 'san', Star: 'staar', Flower: 'flau-ər', Tree: 'trii',
    Ball: 'bol', Balloon: 'bə-luun', Gift: 'gift', Book: 'buk',
    Guitar: 'gi-taar', Piano: 'pi-a-no', Drum: 'dram',
    Bear: 'ber', Tiger: 'tai-gər', Rabbit: 'ra-bit', Duck: 'dak', Frog: 'frog', Fish: 'fish',
    Pizza: 'piit-sə', Cake: 'keik', 'Ice Cream': 'ais kriim', Cookie: 'ku-ki', Sandwich: 'sand-wich', 'Hot Dog': 'hot dog',
    House: 'haus', Heart: 'haart', Crown: 'kraun', Key: 'kii', Clock: 'klok', Phone: 'foun',
    Horse: 'hors', Panda: 'pan-də', Koala: 'ko-aa-lə', Penguin: 'pen-gwin', Owl: 'aul', Butterfly: 'ba-tər-flai',
    Hamburger: 'ham-bər-gər', Donut: 'do-nat', Lollipop: 'lo-li-pop', Candy: 'kan-di', Popcorn: 'pop-korn', Pretzel: 'pret-səl',
    Umbrella: 'am-bre-lə', Rainbow: 'rein-bou', Moon: 'muun', Cloud: 'klaud', Snowflake: 'snou-fleik', Fire: 'fai-ər',
  },
  lv: {
    Cow: 'govs', Pig: 'tsuu-ka', Dog: 'suns', Cat: 'ka-ķis', Sheep: 'ai-ta', Lion: 'lau-va', Monkey: 'peer-ti-ķis', Elephant: 'zi-lo-nis', Giraffe: 'ži-ra-fe',
    Apple: 'aa-bols', Banana: 'ba-naans', Strawberry: 'ze-me-ne', Orange: 'a-pel-siins', Grapes: 'vii-no-gas',
    Carrot: 'bur-kaans', Broccoli: 'bro-ko-lis', Tomato: 'to-maats', Potato: 'kar-tu-pe-lis', 'Bell Pepper': 'pap-ri-ka',
    Car: 'ma-shii-na', Bus: 'au-to-buss', Airplane: 'lid-ma-shii-na', Train: 'vil-ciens', Boat: 'lai-va', Rocket: 'ra-ķe-te',
    Sun: 'sau-le', Star: 'zvaigz-ne', Flower: 'pu-ķe', Tree: 'koks',
    Ball: 'bum-ba', Balloon: 'ba-lons', Gift: 'daa-va-na', Book: 'graa-ma-ta',
    Guitar: 'ģi-taa-ra', Piano: 'kla-vie-res', Drum: 'bun-gas',
    Bear: 'laa-cis', Tiger: 'tii-ģe-ris', Rabbit: 'tru-sis', Duck: 'pii-lii-te', Frog: 'var-de', Fish: 'zivs',
    Pizza: 'pi-ca', Cake: 'kuu-ka', 'Ice Cream': 'sal-dee-jums', Cookie: 'ce-pums', Sandwich: 'sviest-mai-ze', 'Hot Dog': 'hot-dogs',
    House: 'maa-ja', Heart: 'sirds', Crown: 'kro-nis', Key: 'at-slee-ga', Clock: 'pulk-ste-nis', Phone: 'taal-ru-nis',
    Horse: 'zirgs', Panda: 'pan-da', Koala: 'ko-a-la', Penguin: 'ping-viins', Owl: 'puu-ce', Butterfly: 'tau-riņš',
    Hamburger: 'ham-bur-gers', Donut: 'do-nuts', Lollipop: 'le-de-nii-te', Candy: 'kon-fek-te', Popcorn: 'pop-korns', Pretzel: 'bre-ce-lis',
    Umbrella: 'lie-tus-sargs', Rainbow: 'va-ra-viik-sne', Moon: 'mee-ness', Cloud: 'maa-ko-nis', Snowflake: 'snieg-paar-sla', Fire: 'u-guns',
  },
  et: {
    Cow: 'lehm', Pig: 'si-ga', Dog: 'koer', Cat: 'kass', Sheep: 'lam-mas', Lion: 'lõ-vi', Monkey: 'ahv', Elephant: 'e-le-vant', Giraffe: 'kael-kir-jak',
    Apple: 'õun', Banana: 'ba-naan', Strawberry: 'maa-si-kas', Orange: 'a-pel-sin', Grapes: 'vii-na-mar-jad',
    Carrot: 'por-gand', Broccoli: 'bro-ko-li', Tomato: 'to-mat', Potato: 'kar-tul', 'Bell Pepper': 'pap-ri-ka',
    Car: 'au-to', Bus: 'buss', Airplane: 'len-nuk', Train: 'rong', Boat: 'paat', Rocket: 'ra-kett',
    Sun: 'päi-kes', Star: 'täht', Flower: 'lill', Tree: 'puu',
    Ball: 'pall', Balloon: 'õhu-pall', Gift: 'kin-gi-tus', Book: 'raa-mat',
    Guitar: 'ki-tarr', Piano: 'kla-ver', Drum: 'trumm',
    Bear: 'ka-ru', Tiger: 'tii-ger', Rabbit: 'jä-nes', Duck: 'part', Frog: 'konn', Fish: 'ka-la',
    Pizza: 'pit-sa', Cake: 'kook', 'Ice Cream': 'jää-tis', Cookie: 'küp-sis', Sandwich: 'või-leib', 'Hot Dog': 'hot-dog',
    House: 'ma-ja', Heart: 'sü-da', Crown: 'kroon', Key: 'võ-ti', Clock: 'kell', Phone: 'te-le-fon',
    Horse: 'ho-bu-ne', Panda: 'pan-da', Koala: 'ko-aa-la', Penguin: 'ping-viin', Owl: 'öö-kull', Butterfly: 'lib-li-kas',
    Hamburger: 'ham-bur-ger', Donut: 'sõõ-rik', Lollipop: 'pul-ga-komm', Candy: 'komm', Popcorn: 'pop-korn', Pretzel: 'krin-gel',
    Umbrella: 'vih-ma-va-ri', Rainbow: 'vi-ker-kaar', Moon: 'kuu', Cloud: 'pilv', Snowflake: 'lu-me-hel-ves', Fire: 'tu-li',
  },
  lt: {
    Cow: 'kar-vė', Pig: 'kiau-lė', Dog: 'šuo', Cat: 'ka-tė', Sheep: 'a-vis', Lion: 'liū-tas', Monkey: 'bež-džio-nė', Elephant: 'dram-blys', Giraffe: 'ži-ra-fa',
    Apple: 'o-buo-lys', Banana: 'ba-na-nas', Strawberry: 'braš-kė', Orange: 'a-pel-si-nas', Grapes: 'vy-nuo-gės',
    Carrot: 'mor-ka', Broccoli: 'bro-ko-lis', Tomato: 'po-mi-do-ras', Potato: 'bul-vė', 'Bell Pepper': 'pap-ri-ka',
    Car: 'au-to-mo-bi-lis', Bus: 'au-to-bu-sas', Airplane: 'lėk-tu-vas', Train: 'trau-ki-nys', Boat: 'val-tis', Rocket: 'ra-ke-ta',
    Sun: 'sau-lė', Star: 'žvaigž-dė', Flower: 'gė-lė', Tree: 'me-dis',
    Ball: 'ka-muo-lys', Balloon: 'ba-lio-nas', Gift: 'do-va-na', Book: 'kny-ga',
    Guitar: 'gi-ta-ra', Piano: 'pia-ni-nas', Drum: 'būg-nas',
    Bear: 'lo-kys', Tiger: 'tig-ras', Rabbit: 'zui-kis', Duck: 'an-tis', Frog: 'var-lė', Fish: 'žu-vis',
    Pizza: 'pi-ca', Cake: 'tor-tas', 'Ice Cream': 'le-dai', Cookie: 'sau-sai-nis', Sandwich: 'su-muš-ti-nis', 'Hot Dog': 'deš-rai-nis',
    House: 'na-mas', Heart: 'šir-dis', Crown: 'ka-rū-na', Key: 'rak-tas', Clock: 'laik-ro-dis', Phone: 'te-le-fo-nas',
    Horse: 'ark-lys', Panda: 'pan-da', Koala: 'ko-a-la', Penguin: 'ping-vi-nas', Owl: 'pe-lė-da', Butterfly: 'dru-ge-lis',
    Hamburger: 'mė-sai-nis', Donut: 'spur-ga', Lollipop: 'le-di-nu-kas', Candy: 'sal-dai-nis', Popcorn: 'spra-gė-siai', Pretzel: 'ries-tai-nys',
    Umbrella: 'skė-tis', Rainbow: 'vai-vo-rykš-tė', Moon: 'mė-nu-lis', Cloud: 'de-be-sis', Snowflake: 'snai-gė', Fire: 'ug-nis',
  },
  es: {
    Cow: 'ba-ka', Pig: 'ser-do', Dog: 'pe-rro', Cat: 'ga-to', Sheep: 'o-be-ja', Lion: 'le-on', Monkey: 'mo-no', Elephant: 'e-le-fan-te', Giraffe: 'ji-ra-fa',
    Apple: 'man-sa-na', Banana: 'pla-ta-no', Strawberry: 'fre-sa', Orange: 'na-ran-ja', Grapes: 'u-bas',
    Carrot: 'sa-na-o-ria', Broccoli: 'bro-ko-li', Tomato: 'to-ma-te', Potato: 'pa-ta-ta', 'Bell Pepper': 'pi-mien-to',
    Car: 'ko-che', Bus: 'au-to-bus', Airplane: 'a-bion', Train: 'tren', Boat: 'bar-ko', Rocket: 'ko-e-te',
    Sun: 'sol', Star: 'es-tre-ya', Flower: 'flor', Tree: 'ar-bol',
    Ball: 'pe-lo-ta', Balloon: 'glo-bo', Gift: 're-ga-lo', Book: 'li-bro',
    Guitar: 'gi-ta-rra', Piano: 'pia-no', Drum: 'tam-bor',
    Bear: 'o-so', Tiger: 'ti-gre', Rabbit: 'ko-ne-jo', Duck: 'pa-to', Frog: 'ra-na', Fish: 'pes',
    Pizza: 'pit-sa', Cake: 'pas-tel', 'Ice Cream': 'e-la-do', Cookie: 'ga-ye-ta', Sandwich: 'sand-wich', 'Hot Dog': 'pe-rro ka-lien-te',
    House: 'ka-sa', Heart: 'ko-ra-son', Crown: 'ko-ro-na', Key: 'ya-be', Clock: 're-loj', Phone: 'te-le-fo-no',
    Horse: 'ka-ba-yo', Panda: 'pan-da', Koala: 'ko-a-la', Penguin: 'pin-güi-no', Owl: 'bu-o', Butterfly: 'ma-ri-po-sa',
    Hamburger: 'am-bur-ge-sa', Donut: 'do-nat', Lollipop: 'pi-ru-le-ta', Candy: 'dul-se', Popcorn: 'pa-lo-mi-tas', Pretzel: 'pret-sel',
    Umbrella: 'pa-ra-guas', Rainbow: 'ar-ko-i-ris', Moon: 'lu-na', Cloud: 'nu-be', Snowflake: 'ko-po de nie-be', Fire: 'fue-go',
  },
  fr: {
    Cow: 'vash', Pig: 'ko-shon', Dog: 'shien', Cat: 'sha', Sheep: 'mu-ton', Lion: 'li-on', Monkey: 'senj', Elephant: 'e-le-fan', Giraffe: 'ji-raf',
    Apple: 'pom', Banana: 'ba-nan', Strawberry: 'frez', Orange: 'o-ranj', Grapes: 're-zen',
    Carrot: 'ka-rot', Broccoli: 'bro-ko-li', Tomato: 'to-mat', Potato: 'pom-de-ter', 'Bell Pepper': 'pwa-vron',
    Car: 'vwa-tür', Bus: 'büs', Airplane: 'a-vion', Train: 'tren', Boat: 'ba-to', Rocket: 'fü-ze',
    Sun: 'so-lei', Star: 'e-twal', Flower: 'flör', Tree: 'arbr',
    Ball: 'bal', Balloon: 'ba-lon', Gift: 'ka-do', Book: 'livr',
    Guitar: 'gi-tar', Piano: 'pia-no', Drum: 'tam-bur',
    Bear: 'urs', Tiger: 'tigr', Rabbit: 'la-pen', Duck: 'ka-nar', Frog: 'gre-nui', Fish: 'pwa-son',
    Pizza: 'pit-sa', Cake: 'ga-to', 'Ice Cream': 'glas', Cookie: 'bis-küi', Sandwich: 'sand-wish', 'Hot Dog': 'ot-dog',
    House: 'me-zon', Heart: 'kör', Crown: 'ku-ron', Key: 'kle', Clock: 'or-loj', Phone: 'te-le-fon',
    Horse: 'she-val', Panda: 'pan-da', Koala: 'ko-a-la', Penguin: 'man-sho', Owl: 'i-bu', Butterfly: 'pa-pi-yon',
    Hamburger: 'am-bur-ger', Donut: 'do-nöt', Lollipop: 'sü-set', Candy: 'bon-bon', Popcorn: 'pop-korn', Pretzel: 'bret-sel',
    Umbrella: 'pa-ra-plüi', Rainbow: 'ark-an-siel', Moon: 'lün', Cloud: 'nüaj', Snowflake: 'flo-kon', Fire: 'fö',
  },
  de: {
    Cow: 'kuu', Pig: 'shvain', Dog: 'hunt', Cat: 'kat-se', Sheep: 'shaaf', Lion: 'lö-ve', Monkey: 'a-fe', Elephant: 'e-le-fant', Giraffe: 'ji-ra-fe',
    Apple: 'ap-fel', Banana: 'ba-naa-ne', Strawberry: 'ert-beer-e', Orange: 'o-ran-je', Grapes: 'trau-ben',
    Carrot: 'ka-ro-te', Broccoli: 'bro-ko-li', Tomato: 'to-maa-te', Potato: 'kar-to-fel', 'Bell Pepper': 'pap-ri-ka',
    Car: 'au-to', Bus: 'bus', Airplane: 'flug-tsoig', Train: 'tsug', Boat: 'boot', Rocket: 'ra-kee-te',
    Sun: 'zo-ne', Star: 'shtern', Flower: 'bluu-me', Tree: 'baum',
    Ball: 'bal', Balloon: 'luft-ba-lon', Gift: 'ge-shenk', Book: 'buuh',
    Guitar: 'gi-ta-re', Piano: 'kla-vier', Drum: 'tro-mel',
    Bear: 'beer', Tiger: 'tii-ger', Rabbit: 'haa-ze', Duck: 'en-te', Frog: 'frosh', Fish: 'fish',
    Pizza: 'pit-sa', Cake: 'kuu-hen', 'Ice Cream': 'ais', Cookie: 'keks', Sandwich: 'zend-vich', 'Hot Dog': 'hot-dog',
    House: 'haus', Heart: 'herts', Crown: 'kroo-ne', Key: 'shlü-sel', Clock: 'uur', Phone: 'te-le-fon',
    Horse: 'pfert', Panda: 'pan-da', Koala: 'ko-aa-la', Penguin: 'ping-guin', Owl: 'oi-le', Butterfly: 'shme-ter-ling',
    Hamburger: 'ham-bur-ger', Donut: 'do-nat', Lollipop: 'lut-sher', Candy: 'züs-sig-kait', Popcorn: 'pop-korn', Pretzel: 'bre-tsel',
    Umbrella: 're-gen-shirm', Rainbow: 're-gen-bo-gen', Moon: 'mont', Cloud: 'vol-ke', Snowflake: 'shnee-flo-ke', Fire: 'foi-er',
  },
};

export const availableLanguages = [
  { code: 'en', flag: '🇬🇧', name: 'English' },
  { code: 'lv', flag: '🇱🇻', name: 'Latviešu' },
  { code: 'lt', flag: '🇱🇹', name: 'Lietuvių' },
  { code: 'et', flag: '🇪🇪', name: 'Eesti' },
  { code: 'es', flag: '🇪🇸', name: 'Español' },
  { code: 'fr', flag: '🇫🇷', name: 'Français' },
  { code: 'de', flag: '🇩🇪', name: 'Deutsch' },
];
