import type { Item } from './types';

export const ALL_ITEMS: Item[] = [
  // Animals
  { name: 'Cow', emoji: '🐄', soundFrequency: 180, color: 'bg-sky-200', textColor: 'text-sky-800' },
  { name: 'Pig', emoji: '🐖', soundFrequency: 320, color: 'bg-pink-200', textColor: 'text-pink-800' },
  { name: 'Dog', emoji: '🐕', soundFrequency: 250, color: 'bg-amber-200', textColor: 'text-amber-800' },
  { name: 'Cat', emoji: '🐈', soundFrequency: 440, color: 'bg-slate-300', textColor: 'text-slate-800' },
  { name: 'Sheep', emoji: '🐑', soundFrequency: 380, color: 'bg-lime-200', textColor: 'text-lime-800' },
  { name: 'Lion', emoji: '🦁', soundFrequency: 200, color: 'bg-orange-300', textColor: 'text-orange-900' },
  { name: 'Monkey', emoji: '🐒', soundFrequency: 460, color: 'bg-yellow-400', textColor: 'text-yellow-900' },
  { name: 'Elephant', emoji: '🐘', soundFrequency: 140, color: 'bg-gray-400', textColor: 'text-gray-900' },
  { name: 'Giraffe', emoji: '🦒', soundFrequency: 230, color: 'bg-yellow-300', textColor: 'text-yellow-800' },
  
  // Fruits
  { name: 'Apple', emoji: '🍎', soundFrequency: 400, color: 'bg-red-200', textColor: 'text-red-800' },
  { name: 'Banana', emoji: '🍌', soundFrequency: 420, color: 'bg-yellow-200', textColor: 'text-yellow-800' },
  { name: 'Strawberry', emoji: '🍓', soundFrequency: 450, color: 'bg-red-300', textColor: 'text-red-900' },
  { name: 'Orange', emoji: '🍊', soundFrequency: 480, color: 'bg-orange-200', textColor: 'text-orange-800' },
  { name: 'Grapes', emoji: '🍇', soundFrequency: 500, color: 'bg-purple-200', textColor: 'text-purple-800' },

  // Vegetables
  { name: 'Carrot', emoji: '🥕', soundFrequency: 300, color: 'bg-orange-300', textColor: 'text-orange-900' },
  { name: 'Broccoli', emoji: '🥦', soundFrequency: 330, color: 'bg-green-200', textColor: 'text-green-800' },
  { name: 'Tomato', emoji: '🍅', soundFrequency: 350, color: 'bg-red-400', textColor: 'text-red-900' },
  { name: 'Potato', emoji: '🥔', soundFrequency: 280, color: 'bg-yellow-400', textColor: 'text-yellow-900' },
  { name: 'Bell Pepper', emoji: '🫑', soundFrequency: 370, color: 'bg-green-300', textColor: 'text-green-900' },

  // Transport
  { name: 'Car', emoji: '🚗', soundFrequency: 200, color: 'bg-blue-200', textColor: 'text-blue-800' },
  { name: 'Bus', emoji: '🚌', soundFrequency: 150, color: 'bg-yellow-300', textColor: 'text-yellow-900' },
  { name: 'Airplane', emoji: '✈️', soundFrequency: 600, color: 'bg-gray-200', textColor: 'text-gray-800' },
  { name: 'Train', emoji: '🚂', soundFrequency: 220, color: 'bg-red-300', textColor: 'text-red-800' },
  { name: 'Boat', emoji: '⛵️', soundFrequency: 340, color: 'bg-cyan-200', textColor: 'text-cyan-800' },
  { name: 'Rocket', emoji: '🚀', soundFrequency: 650, color: 'bg-slate-500', textColor: 'text-slate-100' },

  // Nature
  { name: 'Sun', emoji: '☀️', soundFrequency: 550, color: 'bg-yellow-200', textColor: 'text-yellow-800' },
  { name: 'Star', emoji: '⭐', soundFrequency: 700, color: 'bg-yellow-300', textColor: 'text-yellow-900' },
  { name: 'Flower', emoji: '🌻', soundFrequency: 520, color: 'bg-green-200', textColor: 'text-green-800' },
  { name: 'Tree', emoji: '🌳', soundFrequency: 160, color: 'bg-lime-300', textColor: 'text-lime-900' },

  // Objects
  { name: 'Ball', emoji: '⚽️', soundFrequency: 310, color: 'bg-gray-200', textColor: 'text-gray-800' },
  { name: 'Balloon', emoji: '🎈', soundFrequency: 470, color: 'bg-red-300', textColor: 'text-red-900' },
  { name: 'Gift', emoji: '🎁', soundFrequency: 530, color: 'bg-teal-200', textColor: 'text-teal-800' },
  { name: 'Book', emoji: '📚', soundFrequency: 270, color: 'bg-blue-300', textColor: 'text-blue-900' },

  // Instruments
  { name: 'Guitar', emoji: '🎸', soundFrequency: 260, color: 'bg-amber-300', textColor: 'text-amber-900' },
  { name: 'Piano', emoji: '🎹', soundFrequency: 490, color: 'bg-gray-300', textColor: 'text-gray-900' },
  { name: 'Drum', emoji: '🥁', soundFrequency: 190, color: 'bg-cyan-300', textColor: 'text-cyan-900' },

  // More Animals
  { name: 'Bear', emoji: '🐻', soundFrequency: 170, color: 'bg-amber-400', textColor: 'text-amber-900' },
  { name: 'Tiger', emoji: '🐅', soundFrequency: 210, color: 'bg-orange-400', textColor: 'text-orange-900' },
  { name: 'Rabbit', emoji: '🐰', soundFrequency: 360, color: 'bg-pink-300', textColor: 'text-pink-900' },
  { name: 'Duck', emoji: '🦆', soundFrequency: 290, color: 'bg-yellow-400', textColor: 'text-yellow-900' },
  { name: 'Frog', emoji: '🐸', soundFrequency: 380, color: 'bg-green-400', textColor: 'text-green-900' },
  { name: 'Fish', emoji: '🐟', soundFrequency: 240, color: 'bg-blue-300', textColor: 'text-blue-900' },

  // More Food
  { name: 'Pizza', emoji: '🍕', soundFrequency: 390, color: 'bg-orange-300', textColor: 'text-orange-900' },
  { name: 'Cake', emoji: '🍰', soundFrequency: 410, color: 'bg-pink-200', textColor: 'text-pink-800' },
  { name: 'Ice Cream', emoji: '🍦', soundFrequency: 430, color: 'bg-blue-200', textColor: 'text-blue-800' },
  { name: 'Cookie', emoji: '🍪', soundFrequency: 350, color: 'bg-amber-200', textColor: 'text-amber-800' },
  { name: 'Sandwich', emoji: '🥪', soundFrequency: 320, color: 'bg-yellow-300', textColor: 'text-yellow-900' },
  { name: 'Hot Dog', emoji: '🌭', soundFrequency: 340, color: 'bg-red-300', textColor: 'text-red-900' },

  // More Objects
  { name: 'House', emoji: '🏠', soundFrequency: 180, color: 'bg-red-200', textColor: 'text-red-800' },
  { name: 'Heart', emoji: '❤️', soundFrequency: 440, color: 'bg-red-400', textColor: 'text-red-100' },
  { name: 'Crown', emoji: '👑', soundFrequency: 520, color: 'bg-yellow-400', textColor: 'text-yellow-900' },
  { name: 'Key', emoji: '🗝️', soundFrequency: 300, color: 'bg-yellow-300', textColor: 'text-yellow-900' },
  { name: 'Clock', emoji: '🕐', soundFrequency: 280, color: 'bg-blue-300', textColor: 'text-blue-900' },
  { name: 'Phone', emoji: '📱', soundFrequency: 460, color: 'bg-gray-300', textColor: 'text-gray-900' },

  // Even More Animals
  { name: 'Horse', emoji: '🐴', soundFrequency: 220, color: 'bg-amber-300', textColor: 'text-amber-900' },
  { name: 'Panda', emoji: '🐼', soundFrequency: 190, color: 'bg-gray-200', textColor: 'text-gray-800' },
  { name: 'Koala', emoji: '🐨', soundFrequency: 250, color: 'bg-gray-300', textColor: 'text-gray-900' },
  { name: 'Penguin', emoji: '🐧', soundFrequency: 270, color: 'bg-slate-300', textColor: 'text-slate-900' },
  { name: 'Owl', emoji: '🦉', soundFrequency: 310, color: 'bg-amber-400', textColor: 'text-amber-900' },
  { name: 'Butterfly', emoji: '🦋', soundFrequency: 480, color: 'bg-purple-200', textColor: 'text-purple-800' },

  // More Food
  { name: 'Hamburger', emoji: '🍔', soundFrequency: 370, color: 'bg-yellow-400', textColor: 'text-yellow-900' },
  { name: 'Donut', emoji: '🍩', soundFrequency: 420, color: 'bg-pink-300', textColor: 'text-pink-900' },
  { name: 'Lollipop', emoji: '🍭', soundFrequency: 450, color: 'bg-pink-200', textColor: 'text-pink-800' },
  { name: 'Candy', emoji: '🍬', soundFrequency: 470, color: 'bg-red-200', textColor: 'text-red-800' },
  { name: 'Popcorn', emoji: '🍿', soundFrequency: 400, color: 'bg-yellow-300', textColor: 'text-yellow-900' },
  { name: 'Pretzel', emoji: '🥨', soundFrequency: 380, color: 'bg-amber-200', textColor: 'text-amber-800' },

  // More Objects
  { name: 'Umbrella', emoji: '☂️', soundFrequency: 330, color: 'bg-blue-200', textColor: 'text-blue-800' },
  { name: 'Rainbow', emoji: '🌈', soundFrequency: 540, color: 'bg-gradient-to-r from-red-200 to-purple-200', textColor: 'text-purple-800' },
  { name: 'Moon', emoji: '🌙', soundFrequency: 480, color: 'bg-slate-200', textColor: 'text-slate-800' },
  { name: 'Cloud', emoji: '☁️', soundFrequency: 360, color: 'bg-gray-200', textColor: 'text-gray-800' },
  { name: 'Snowflake', emoji: '❄️', soundFrequency: 420, color: 'bg-blue-100', textColor: 'text-blue-600' },
  { name: 'Fire', emoji: '🔥', soundFrequency: 580, color: 'bg-red-300', textColor: 'text-red-900' },
];

export const translations: Record<string, Record<string, string>> = {
  en: {
    Settings: 'Settings',
    language: 'Language',
    itemCount: 'Number of items',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    selectGame: 'Select a Game',
    popItGameTitle: 'Name It!',
    findItGameTitle: 'Find It!',
    vroomGameTitle: 'Vroom!',
    launches: 'launches',
    findThe: 'Where is',
    correct: 'right',
    total: 'total',
    amazing: 'Amazing!',
    great: 'Great job!',
    good: 'Good work!',
    keepGoing: 'Keep going!',
    learning: 'Keep learning!',
    Cow: 'Cow', Pig: 'Pig', Dog: 'Dog', Cat: 'Cat', Sheep: 'Sheep', Lion: 'Lion', Monkey: 'Monkey', Elephant: 'Elephant', Giraffe: 'Giraffe',
    Apple: 'Apple', Banana: 'Banana', Strawberry: 'Strawberry', Orange: 'Orange', Grapes: 'Grapes',
    Carrot: 'Carrot', Broccoli: 'Broccoli', Tomato: 'Tomato', Potato: 'Potato', 'Bell Pepper': 'Bell Pepper',
    Car: 'Car', Bus: 'Bus', Airplane: 'Airplane', Train: 'Train', Boat: 'Boat', Rocket: 'Rocket',
    Sun: 'Sun', Star: 'Star', Flower: 'Flower', Tree: 'Tree',
    Ball: 'Ball', Balloon: 'Balloon', Gift: 'Gift', Book: 'Book',
    Guitar: 'Guitar', Piano: 'Piano', Drum: 'Drum',
    Bear: 'Bear', Tiger: 'Tiger', Rabbit: 'Rabbit', Duck: 'Duck', Frog: 'Frog', Fish: 'Fish',
    Pizza: 'Pizza', Cake: 'Cake', 'Ice Cream': 'Ice Cream', Cookie: 'Cookie', Sandwich: 'Sandwich', 'Hot Dog': 'Hot Dog',
    House: 'House', Heart: 'Heart', Crown: 'Crown', Key: 'Key', Clock: 'Clock', Phone: 'Phone',
    Horse: 'Horse', Panda: 'Panda', Koala: 'Koala', Penguin: 'Penguin', Owl: 'Owl', Butterfly: 'Butterfly',
    Hamburger: 'Hamburger', Donut: 'Donut', Lollipop: 'Lollipop', Candy: 'Candy', Popcorn: 'Popcorn', Pretzel: 'Pretzel',
    Umbrella: 'Umbrella', Rainbow: 'Rainbow', Moon: 'Moon', Cloud: 'Cloud', Snowflake: 'Snowflake', Fire: 'Fire',
  },
  lv: {
    Settings: 'Iestatījumi',
    language: 'Valoda',
    itemCount: 'Objektu skaits',
    difficulty: 'Grūtības pakāpe',
    easy: 'Viegli',
    medium: 'Vidēji',
    hard: 'Grūti',
    selectGame: 'Teo spēles',
    popItGameTitle: 'Kas?',
    findItGameTitle: 'Kur?',
    vroomGameTitle: 'Brrūm!',
    launches: 'palaisti',
    findThe: 'Kur ir',
    correct: 'pareizi',
    total: 'kopā',
    amazing: 'Lieliski!',
    great: 'Lielisks darbs!',
    good: 'Labi!',
    keepGoing: 'Turpinājiet!',
    learning: 'Mācieties tālāk!',
    Cow: 'Govs', Pig: 'Cūka', Dog: 'Suns', Cat: 'Kaķis', Sheep: 'Aita', Lion: 'Lauva', Monkey: 'Pērtiķis', Elephant: 'Zilonis', Giraffe: 'Žirafe',
    Apple: 'Ābols', Banana: 'Banāns', Strawberry: 'Zemene', Orange: 'Apelsīns', Grapes: 'Vīnogas',
    Carrot: 'Burkāns', Broccoli: 'Brokolis', Tomato: 'Tomāts', Potato: 'Kartupelis', 'Bell Pepper': 'Paprika',
    Car: 'Mašīna', Bus: 'Autobuss', Airplane: 'Lidmašīna', Train: 'Vilciens', Boat: 'Laiva', Rocket: 'Raķete',
    Sun: 'Saule', Star: 'Zvaigzne', Flower: 'Puķe', Tree: 'Koks',
    Ball: 'Bumba', Balloon: 'Balons', Gift: 'Dāvana', Book: 'Grāmata',
    Guitar: 'Ģitāra', Piano: 'Klavieres', Drum: 'Bungas',
    Bear: 'Lācis', Tiger: 'Tīģeris', Rabbit: 'Trusis', Duck: 'Pīlīte', Frog: 'Varde', Fish: 'Zivs',
    Pizza: 'Pica', Cake: 'Kūka', 'Ice Cream': 'Saldējums', Cookie: 'Cepums', Sandwich: 'Sviestmaize', 'Hot Dog': 'Hotdogs',
    House: 'Māja', Heart: 'Sirds', Crown: 'Kronis', Key: 'Atslēga', Clock: 'Pulkstenis', Phone: 'Tālrunis',
    Horse: 'Zirgs', Panda: 'Panda', Koala: 'Koala', Penguin: 'Pingvīns', Owl: 'Pūce', Butterfly: 'Tauriņš',
    Hamburger: 'Hamburgers', Donut: 'Donuts', Lollipop: 'Konfekte uz kociņa', Candy: 'Konfekte', Popcorn: 'Popkorns', Pretzel: 'Precelis',
    Umbrella: 'Lietussargs', Rainbow: 'Varavīksne', Moon: 'Mēness', Cloud: 'Mākonis', Snowflake: 'Sniegpārsla', Fire: 'Uguns',
  },
  es: {
    Settings: 'Ajustes',
    language: 'Idioma',
    itemCount: 'Número de objetos',
    difficulty: 'Dificultad',
    easy: 'Fácil',
    medium: 'Medio',
    hard: 'Difícil',
    selectGame: 'Elige un juego',
    popItGameTitle: '¡Nómbralo!',
    findItGameTitle: '¡Encuéntralo!',
    vroomGameTitle: '¡Vroom!',
    launches: 'lanzamientos',
    findThe: '¿Dónde está',
    correct: 'correctas',
    total: 'total',
    amazing: '¡Increíble!',
    great: '¡Excelente!',
    good: '¡Bien!',
    keepGoing: '¡Sigue así!',
    learning: '¡Sigue aprendiendo!',
    Cow: 'Vaca', Pig: 'Cerdo', Dog: 'Perro', Cat: 'Gato', Sheep: 'Oveja', Lion: 'León', Monkey: 'Mono', Elephant: 'Elefante', Giraffe: 'Jirafa',
    Apple: 'Manzana', Banana: 'Plátano', Strawberry: 'Fresa', Orange: 'Naranja', Grapes: 'Uvas',
    Carrot: 'Zanahoria', Broccoli: 'Brócoli', Tomato: 'Tomate', Potato: 'Patata', 'Bell Pepper': 'Pimiento',
    Car: 'Coche', Bus: 'Autobús', Airplane: 'Avión', Train: 'Tren', Boat: 'Barco', Rocket: 'Cohete',
    Sun: 'Sol', Star: 'Estrella', Flower: 'Flor', Tree: 'Árbol',
    Ball: 'Pelota', Balloon: 'Globo', Gift: 'Regalo', Book: 'Libro',
    Guitar: 'Guitarra', Piano: 'Piano', Drum: 'Tambor',
    Bear: 'Oso', Tiger: 'Tigre', Rabbit: 'Conejo', Duck: 'Pato', Frog: 'Rana', Fish: 'Pez',
    Pizza: 'Pizza', Cake: 'Pastel', 'Ice Cream': 'Helado', Cookie: 'Galleta', Sandwich: 'Sándwich', 'Hot Dog': 'Perro Caliente',
    House: 'Casa', Heart: 'Corazón', Crown: 'Corona', Key: 'Llave', Clock: 'Reloj', Phone: 'Teléfono',
    Horse: 'Caballo', Panda: 'Panda', Koala: 'Koala', Penguin: 'Pingüino', Owl: 'Búho', Butterfly: 'Mariposa',
    Hamburger: 'Hamburguesa', Donut: 'Donut', Lollipop: 'Piruleta', Candy: 'Dulce', Popcorn: 'Palomitas', Pretzel: 'Pretzel',
    Umbrella: 'Paraguas', Rainbow: 'Arcoíris', Moon: 'Luna', Cloud: 'Nube', Snowflake: 'Copo de Nieve', Fire: 'Fuego',
  },
  fr: {
    Settings: 'Paramètres',
    language: 'Langue',
    itemCount: "Nombre d'objets",
    difficulty: 'Difficulté',
    easy: 'Facile',
    medium: 'Moyen',
    hard: 'Difficile',
    selectGame: 'Choisissez un jeu',
    popItGameTitle: 'Nomme-le !',
    findItGameTitle: 'Trouve-le !',
    vroomGameTitle: 'Vroum !',
    launches: 'lancements',
    findThe: 'Où est',
    correct: 'correctes',
    total: 'total',
    amazing: 'Incroyable !',
    great: 'Excellent !',
    good: 'Bien !',
    keepGoing: 'Continue !',
    learning: 'Continue d\'apprendre !',
    Cow: 'Vache', Pig: 'Cochon', Dog: 'Chien', Cat: 'Chat', Sheep: 'Mouton', Lion: 'Lion', Monkey: 'Singe', Elephant: 'Éléphant', Giraffe: 'Girafe',
    Apple: 'Pomme', Banana: 'Banane', Strawberry: 'Fraise', Orange: 'Orange', Grapes: 'Raisins',
    Carrot: 'Carotte', Broccoli: 'Brocoli', Tomato: 'Tomate', 'Bell Pepper': 'Poivron', Potato: 'Pomme de terre',
    Car: 'Voiture', Bus: 'Bus', Airplane: 'Avion', Train: 'Train', Boat: 'Bateau', Rocket: 'Fusée',
    Sun: 'Soleil', Star: 'Étoile', Flower: 'Fleur', Tree: 'Arbre',
    Ball: 'Balle', Balloon: 'Ballon', Gift: 'Cadeau', Book: 'Livre',
    Guitar: 'Guitare', Piano: 'Piano', Drum: 'Tambour',
    Bear: 'Ours', Tiger: 'Tigre', Rabbit: 'Lapin', Duck: 'Canard', Frog: 'Grenouille', Fish: 'Poisson',
    Pizza: 'Pizza', Cake: 'Gâteau', 'Ice Cream': 'Glace', Cookie: 'Biscuit', Sandwich: 'Sandwich', 'Hot Dog': 'Hot Dog',
    House: 'Maison', Heart: 'Cœur', Crown: 'Couronne', Key: 'Clé', Clock: 'Horloge', Phone: 'Téléphone',
    Horse: 'Cheval', Panda: 'Panda', Koala: 'Koala', Penguin: 'Pingouin', Owl: 'Hibou', Butterfly: 'Papillon',
    Hamburger: 'Hamburger', Donut: 'Donut', Lollipop: 'Sucette', Candy: 'Bonbon', Popcorn: 'Popcorn', Pretzel: 'Bretzel',
    Umbrella: 'Parapluie', Rainbow: 'Arc-en-ciel', Moon: 'Lune', Cloud: 'Nuage', Snowflake: 'Flocon de Neige', Fire: 'Feu',
  },
  de: {
    Settings: 'Einstellungen',
    language: 'Sprache',
    itemCount: 'Anzahl der Objekte',
    difficulty: 'Schwierigkeit',
    easy: 'Leicht',
    medium: 'Mittel',
    hard: 'Schwer',
    selectGame: 'Wähle ein Spiel',
    popItGameTitle: 'Benenne es!',
    findItGameTitle: 'Finde es!',
    vroomGameTitle: 'Brumm!',
    launches: 'Starts',
    findThe: 'Wo ist',
    correct: 'richtig',
    total: 'gesamt',
    amazing: 'Unglaublich!',
    great: 'Großartig!',
    good: 'Gut!',
    keepGoing: 'Weiter so!',
    learning: 'Lerne weiter!',
    Cow: 'Kuh', Pig: 'Schwein', Dog: 'Hund', Cat: 'Katze', Sheep: 'Schaf', Lion: 'Löwe', Monkey: 'Affe', Elephant: 'Elefant', Giraffe: 'Giraffe',
    Apple: 'Apfel', Banana: 'Banane', Strawberry: 'Erdbeere', Orange: 'Orange', Grapes: 'Trauben',
    Carrot: 'Karotte', Broccoli: 'Brokkoli', Tomato: 'Tomate', Potato: 'Kartoffel', 'Bell Pepper': 'Paprika',
    Car: 'Auto', Bus: 'Bus', Airplane: 'Flugzeug', Train: 'Zug', Boat: 'Boot', Rocket: 'Rakete',
    Sun: 'Sonne', Star: 'Stern', Flower: 'Blume', Tree: 'Baum',
    Ball: 'Ball', Balloon: 'Luftballon', Gift: 'Geschenk', Book: 'Buch',
    Guitar: 'Gitarre', Piano: 'Klavier', Drum: 'Trommel',
    Bear: 'Bär', Tiger: 'Tiger', Rabbit: 'Hase', Duck: 'Ente', Frog: 'Frosch', Fish: 'Fisch',
    Pizza: 'Pizza', Cake: 'Kuchen', 'Ice Cream': 'Eis', Cookie: 'Keks', Sandwich: 'Sandwich', 'Hot Dog': 'Hot Dog',
    House: 'Haus', Heart: 'Herz', Crown: 'Krone', Key: 'Schlüssel', Clock: 'Uhr', Phone: 'Telefon',
    Horse: 'Pferd', Panda: 'Panda', Koala: 'Koala', Penguin: 'Pinguin', Owl: 'Eule', Butterfly: 'Schmetterling',
    Hamburger: 'Hamburger', Donut: 'Donut', Lollipop: 'Lutscher', Candy: 'Süßigkeit', Popcorn: 'Popcorn', Pretzel: 'Brezel',
    Umbrella: 'Regenschirm', Rainbow: 'Regenbogen', Moon: 'Mond', Cloud: 'Wolke', Snowflake: 'Schneeflocke', Fire: 'Feuer',
  }
};

export const availableLanguages = [
  { code: 'en', flag: '🇬🇧', name: 'English' },
  { code: 'lv', flag: '🇱🇻', name: 'Latviešu' },
  { code: 'es', flag: '🇪🇸', name: 'Español' },
  { code: 'fr', flag: '🇫🇷', name: 'Français' },
  { code: 'de', flag: '🇩🇪', name: 'Deutsch' },
];
